[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100 api:app"

[deploy.envs]
PYTHON_VERSION = "3.11" 
